data:
  raw_data_file: data/examples/regression/mroz.csv

model:
  model_type: iv_2sls
  target_variable: lwage
  independent_variables:
    - exper
    - expersq
  endogenous:
    - educ
  instruments:
    - motheduc
    - fatheduc
  cov_type: robust
