# import pandas as pd
# import io

# # Load the TSV file from the URL, handling potential errors
# url = "https://raw.githubusercontent.com/IndEcol/country_converter/refs/heads/master/country_converter/country_data.tsv"

# df = pd.read_csv(url, sep='\t')

# # Create the dictionary with the desired structure, including the mappings.
# dict_country_converter = {
#     "iso2_to_iso3": df[['ISO2','ISO3']].dropna().set_index('ISO2')['ISO3'].to_dict(),
#     "iso3_to_iso2": df.set_index('ISO3')['ISO2'].to_dict(),
# }

# # Create the dictionary with the desired structure, including the mappings.
# dict_country_converter = {
#     "iso2_to_iso3": df[['ISO2', 'ISO3']].dropna().set_index('ISO2')['ISO3'].to_dict(),
#     "iso3_to_iso2": df[['ISO3', 'ISO2']].dropna().set_index('ISO3')['ISO2'].to_dict(),
#     "iso2_to_name_short": df[['ISO2', 'name_short']].dropna().set_index('ISO2')['name_short'].to_dict(),
#     "iso3_to_name_short": df[['ISO3', 'name_short']].dropna().set_index('ISO3')['name_short'].to_dict(),
#     "name_short_to_iso2": df[['name_short', 'ISO2']].dropna().set_index('name_short')['ISO2'].to_dict(),
#     "name_short_to_iso3": df[['name_short', 'ISO3']].dropna().set_index('name_short')['ISO3'].to_dict(),
# }

dict_country = {'iso2_to_iso3': {'AF': 'AFG',
  'AX': 'ALA',
  'AL': 'ALB',
  'DZ': 'DZA',
  'AS': 'ASM',
  'AD': 'AND',
  'AO': 'AGO',
  'AI': 'AIA',
  'AQ': 'ATA',
  'AG': 'ATG',
  'AR': 'ARG',
  'AM': 'ARM',
  'AW': 'ABW',
  'AU': 'AUS',
  'AT': 'AUT',
  'AZ': 'AZE',
  'BS': 'BHS',
  'BH': 'BHR',
  'BD': 'BGD',
  'BB': 'BRB',
  'BY': 'BLR',
  'BE': 'BEL',
  'BZ': 'BLZ',
  'BJ': 'BEN',
  'BM': 'BMU',
  'BT': 'BTN',
  'BO': 'BOL',
  'BQ': 'BES',
  'BA': 'BIH',
  'BW': 'BWA',
  'BV': 'BVT',
  'BR': 'BRA',
  'B1': 'BA1',
  'IO': 'IOT',
  'VG': 'VGB',
  'BN': 'BRN',
  'BG': 'BGR',
  'BF': 'BFA',
  'BI': 'BDI',
  'CV': 'CPV',
  'KH': 'KHM',
  'CM': 'CMR',
  'CA': 'CAN',
  'KY': 'CYM',
  'CF': 'CAF',
  'TD': 'TCD',
  'CL': 'CHL',
  'CN': 'CHN',
  'CX': 'CXR',
  'CC': 'CCK',
  'CO': 'COL',
  'KM': 'COM',
  'CG': 'COG',
  'CK': 'COK',
  'CR': 'CRI',
  'CI': 'CIV',
  'HR': 'HRV',
  'CU': 'CUB',
  'CW': 'CUW',
  'CY': 'CYP',
  'CZ': 'CZE',
  'DK': 'DNK',
  'DJ': 'DJI',
  'DM': 'DMA',
  'DO': 'DOM',
  'CD': 'COD',
  'EC': 'ECU',
  'EG': 'EGY',
  'SV': 'SLV',
  'GQ': 'GNQ',
  'ER': 'ERI',
  'EE': 'EST',
  'SZ': 'SWZ',
  'ET': 'ETH',
  'FO': 'FRO',
  'FK': 'FLK',
  'FJ': 'FJI',
  'FI': 'FIN',
  'FR': 'FRA',
  'GF': 'GUF',
  'PF': 'PYF',
  'TF': 'ATF',
  'GA': 'GAB',
  'GM': 'GMB',
  'GE': 'GEO',
  'DE': 'DEU',
  'GH': 'GHA',
  'GI': 'GIB',
  '^GR$|^EL$': 'GRC',
  'GL': 'GRL',
  'GD': 'GRD',
  'GP': 'GLP',
  'GU': 'GUM',
  'GT': 'GTM',
  'GG': 'GGY',
  'GN': 'GIN',
  'GW': 'GNB',
  'GY': 'GUY',
  'HT': 'HTI',
  'HM': 'HMD',
  'HN': 'HND',
  'HK': 'HKG',
  'HU': 'HUN',
  'IS': 'ISL',
  'IN': 'IND',
  'ID': 'IDN',
  'IR': 'IRN',
  'IQ': 'IRQ',
  'IE': 'IRL',
  'IM': 'IMN',
  'IL': 'ISR',
  'IT': 'ITA',
  'JM': 'JAM',
  'JP': 'JPN',
  'JE': 'JEY',
  'JO': 'JOR',
  'KZ': 'KAZ',
  'KE': 'KEN',
  'KI': 'KIR',
  'XK': 'XKX',
  'KW': 'KWT',
  'KG': 'KGZ',
  'LA': 'LAO',
  'LV': 'LVA',
  'LB': 'LBN',
  'LS': 'LSO',
  'LR': 'LBR',
  'LY': 'LBY',
  'LI': 'LIE',
  'LT': 'LTU',
  'LU': 'LUX',
  'MO': 'MAC',
  'MK': 'MKD',
  'MG': 'MDG',
  'MW': 'MWI',
  'MY': 'MYS',
  'MV': 'MDV',
  'ML': 'MLI',
  'MT': 'MLT',
  'MH': 'MHL',
  'MQ': 'MTQ',
  'MR': 'MRT',
  'MU': 'MUS',
  'YT': 'MYT',
  'MX': 'MEX',
  'FM': 'FSM',
  'MD': 'MDA',
  'MC': 'MCO',
  'MN': 'MNG',
  'ME': 'MNE',
  'MS': 'MSR',
  'MA': 'MAR',
  'MZ': 'MOZ',
  'MM': 'MMR',
  'NR': 'NRU',
  'NP': 'NPL',
  'NL': 'NLD',
  'AN': 'ANT',
  'NC': 'NCL',
  'NZ': 'NZL',
  'NI': 'NIC',
  'NE': 'NER',
  'NG': 'NGA',
  'NU': 'NIU',
  'NF': 'NFK',
  'KP': 'PRK',
  'MP': 'MNP',
  'NO': 'NOR',
  'OM': 'OMN',
  'PK': 'PAK',
  'PW': 'PLW',
  'PS': 'PSE',
  'PA': 'PAN',
  'PG': 'PNG',
  'PY': 'PRY',
  'PE': 'PER',
  'PH': 'PHL',
  'PN': 'PCN',
  'PL': 'POL',
  'PT': 'PRT',
  'PR': 'PRI',
  'QA': 'QAT',
  'RE': 'REU',
  'RO': 'ROU',
  'RU': 'RUS',
  'RW': 'RWA',
  'MF': 'MAF',
  'WS': 'WSM',
  'SM': 'SMR',
  'ST': 'STP',
  'SA': 'SAU',
  'SN': 'SEN',
  'RS': 'SRB',
  'SC': 'SYC',
  'SL': 'SLE',
  'SG': 'SGP',
  'SX': 'SXM',
  'SK': 'SVK',
  'SI': 'SVN',
  'SB': 'SLB',
  'SO': 'SOM',
  'ZA': 'ZAF',
  'GS': 'SGS',
  'KR': 'KOR',
  'SS': 'SSD',
  'SU': 'SUN',
  'ES': 'ESP',
  'LK': 'LKA',
  'BL': 'BLM',
  'SH': 'SHN',
  'KN': 'KNA',
  'LC': 'LCA',
  'PM': 'SPM',
  'VC': 'VCT',
  'SD': 'SDN',
  'SR': 'SUR',
  'SJ': 'SJM',
  'SE': 'SWE',
  'CH': 'CHE',
  'SY': 'SYR',
  'TW': 'TWN',
  'TJ': 'TJK',
  'TZ': 'TZA',
  'TH': 'THA',
  'TL': 'TLS',
  'TG': 'TGO',
  'TK': 'TKL',
  'TO': 'TON',
  'TT': 'TTO',
  'TN': 'TUN',
  'TR': 'TUR',
  'TM': 'TKM',
  'TC': 'TCA',
  'TV': 'TUV',
  'UG': 'UGA',
  'UA': 'UKR',
  'AE': 'ARE',
  '^GB$|^UK$': 'GBR',
  'US': 'USA',
  'UM': 'UMI',
  'VI': 'VIR',
  'UY': 'URY',
  'UZ': 'UZB',
  'VU': 'VUT',
  'VA': 'VAT',
  'VE': 'VEN',
  'VN': 'VNM',
  'WF': 'WLF',
  'EH': 'ESH',
  'YE': 'YEM',
  'ZM': 'ZMB',
  'ZW': 'ZWE'},
 'iso3_to_iso2': {'AFG': 'AF',
  'ALA': 'AX',
  'ALB': 'AL',
  'DZA': 'DZ',
  'ASM': 'AS',
  'AND': 'AD',
  'AGO': 'AO',
  'AIA': 'AI',
  'ATA': 'AQ',
  'ATG': 'AG',
  'ARG': 'AR',
  'ARM': 'AM',
  'ABW': 'AW',
  'AUS': 'AU',
  'AUT': 'AT',
  'AZE': 'AZ',
  'BHS': 'BS',
  'BHR': 'BH',
  'BGD': 'BD',
  'BRB': 'BB',
  'BLR': 'BY',
  'BEL': 'BE',
  'BLZ': 'BZ',
  'BEN': 'BJ',
  'BMU': 'BM',
  'BTN': 'BT',
  'BOL': 'BO',
  'BES': 'BQ',
  'BIH': 'BA',
  'BWA': 'BW',
  'BVT': 'BV',
  'BRA': 'BR',
  'BA1': 'B1',
  'IOT': 'IO',
  'VGB': 'VG',
  'BRN': 'BN',
  'BGR': 'BG',
  'BFA': 'BF',
  'BDI': 'BI',
  'CPV': 'CV',
  'KHM': 'KH',
  'CMR': 'CM',
  'CAN': 'CA',
  'CYM': 'KY',
  'CAF': 'CF',
  'TCD': 'TD',
  'CHL': 'CL',
  'CHN': 'CN',
  'CXR': 'CX',
  'CCK': 'CC',
  'COL': 'CO',
  'COM': 'KM',
  'COG': 'CG',
  'COK': 'CK',
  'CRI': 'CR',
  'CIV': 'CI',
  'HRV': 'HR',
  'CUB': 'CU',
  'CUW': 'CW',
  'CYP': 'CY',
  'CZE': 'CZ',
  'DNK': 'DK',
  'DJI': 'DJ',
  'DMA': 'DM',
  'DOM': 'DO',
  'COD': 'CD',
  'ECU': 'EC',
  'EGY': 'EG',
  'SLV': 'SV',
  'GNQ': 'GQ',
  'ERI': 'ER',
  'EST': 'EE',
  'SWZ': 'SZ',
  'ETH': 'ET',
  'FRO': 'FO',
  'FLK': 'FK',
  'FJI': 'FJ',
  'FIN': 'FI',
  'FRA': 'FR',
  'GUF': 'GF',
  'PYF': 'PF',
  'ATF': 'TF',
  'GAB': 'GA',
  'GMB': 'GM',
  'GEO': 'GE',
  'DEU': 'DE',
  'GHA': 'GH',
  'GIB': 'GI',
  'GRC': '^GR$|^EL$',
  'GRL': 'GL',
  'GRD': 'GD',
  'GLP': 'GP',
  'GUM': 'GU',
  'GTM': 'GT',
  'GGY': 'GG',
  'GIN': 'GN',
  'GNB': 'GW',
  'GUY': 'GY',
  'HTI': 'HT',
  'HMD': 'HM',
  'HND': 'HN',
  'HKG': 'HK',
  'HUN': 'HU',
  'ISL': 'IS',
  'IND': 'IN',
  'IDN': 'ID',
  'IRN': 'IR',
  'IRQ': 'IQ',
  'IRL': 'IE',
  'IMN': 'IM',
  'ISR': 'IL',
  'ITA': 'IT',
  'JAM': 'JM',
  'JPN': 'JP',
  'JEY': 'JE',
  'JOR': 'JO',
  'KAZ': 'KZ',
  'KEN': 'KE',
  'KIR': 'KI',
  'XKX': 'XK',
  'KWT': 'KW',
  'KGZ': 'KG',
  'LAO': 'LA',
  'LVA': 'LV',
  'LBN': 'LB',
  'LSO': 'LS',
  'LBR': 'LR',
  'LBY': 'LY',
  'LIE': 'LI',
  'LTU': 'LT',
  'LUX': 'LU',
  'MAC': 'MO',
  'MKD': 'MK',
  'MDG': 'MG',
  'MWI': 'MW',
  'MYS': 'MY',
  'MDV': 'MV',
  'MLI': 'ML',
  'MLT': 'MT',
  'MHL': 'MH',
  'MTQ': 'MQ',
  'MRT': 'MR',
  'MUS': 'MU',
  'MYT': 'YT',
  'MEX': 'MX',
  'FSM': 'FM',
  'MDA': 'MD',
  'MCO': 'MC',
  'MNG': 'MN',
  'MNE': 'ME',
  'MSR': 'MS',
  'MAR': 'MA',
  'MOZ': 'MZ',
  'MMR': 'MM',
  'NRU': 'NR',
  'NPL': 'NP',
  'NLD': 'NL',
  'ANT': 'AN',
  'NCL': 'NC',
  'NZL': 'NZ',
  'NIC': 'NI',
  'NER': 'NE',
  'NGA': 'NG',
  'NIU': 'NU',
  'NFK': 'NF',
  'PRK': 'KP',
  'MNP': 'MP',
  'NOR': 'NO',
  'OMN': 'OM',
  'PAK': 'PK',
  'PLW': 'PW',
  'PSE': 'PS',
  'PAN': 'PA',
  'PNG': 'PG',
  'PRY': 'PY',
  'PER': 'PE',
  'PHL': 'PH',
  'PCN': 'PN',
  'POL': 'PL',
  'PRT': 'PT',
  'PRI': 'PR',
  'QAT': 'QA',
  'REU': 'RE',
  'ROU': 'RO',
  'RUS': 'RU',
  'RWA': 'RW',
  'MAF': 'MF',
  'WSM': 'WS',
  'SMR': 'SM',
  'STP': 'ST',
  'SAU': 'SA',
  'SEN': 'SN',
  'SRB': 'RS',
  'SYC': 'SC',
  'SLE': 'SL',
  'SGP': 'SG',
  'SXM': 'SX',
  'SVK': 'SK',
  'SVN': 'SI',
  'SLB': 'SB',
  'SOM': 'SO',
  'ZAF': 'ZA',
  'SGS': 'GS',
  'KOR': 'KR',
  'SSD': 'SS',
  'SUN': 'SU',
  'ESP': 'ES',
  'LKA': 'LK',
  'BLM': 'BL',
  'SHN': 'SH',
  'KNA': 'KN',
  'LCA': 'LC',
  'SPM': 'PM',
  'VCT': 'VC',
  'SDN': 'SD',
  'SUR': 'SR',
  'SJM': 'SJ',
  'SWE': 'SE',
  'CHE': 'CH',
  'SYR': 'SY',
  'TWN': 'TW',
  'TJK': 'TJ',
  'TZA': 'TZ',
  'THA': 'TH',
  'TLS': 'TL',
  'TGO': 'TG',
  'TKL': 'TK',
  'TON': 'TO',
  'TTO': 'TT',
  'TUN': 'TN',
  'TUR': 'TR',
  'TKM': 'TM',
  'TCA': 'TC',
  'TUV': 'TV',
  'UGA': 'UG',
  'UKR': 'UA',
  'ARE': 'AE',
  'GBR': '^GB$|^UK$',
  'USA': 'US',
  'UMI': 'UM',
  'VIR': 'VI',
  'URY': 'UY',
  'UZB': 'UZ',
  'VUT': 'VU',
  'VAT': 'VA',
  'VEN': 'VE',
  'VNM': 'VN',
  'WLF': 'WF',
  'ESH': 'EH',
  'YEM': 'YE',
  'ZMB': 'ZM',
  'ZWE': 'ZW'},
 'iso2_to_name_short': {'AF': 'Afghanistan',
  'AX': 'Aland Islands',
  'AL': 'Albania',
  'DZ': 'Algeria',
  'AS': 'American Samoa',
  'AD': 'Andorra',
  'AO': 'Angola',
  'AI': 'Anguilla',
  'AQ': 'Antarctica',
  'AG': 'Antigua and Barbuda',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AW': 'Aruba',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BS': 'Bahamas',
  'BH': 'Bahrain',
  'BD': 'Bangladesh',
  'BB': 'Barbados',
  'BY': 'Belarus',
  'BE': 'Belgium',
  'BZ': 'Belize',
  'BJ': 'Benin',
  'BM': 'Bermuda',
  'BT': 'Bhutan',
  'BO': 'Bolivia',
  'BQ': 'Bonaire, Saint Eustatius and Saba',
  'BA': 'Bosnia and Herzegovina',
  'BW': 'Botswana',
  'BV': 'Bouvet Island',
  'BR': 'Brazil',
  'B1': 'British Antarctic Territories',
  'IO': 'British Indian Ocean Territory',
  'VG': 'British Virgin Islands',
  'BN': 'Brunei Darussalam',
  'BG': 'Bulgaria',
  'BF': 'Burkina Faso',
  'BI': 'Burundi',
  'CV': 'Cabo Verde',
  'KH': 'Cambodia',
  'CM': 'Cameroon',
  'CA': 'Canada',
  'KY': 'Cayman Islands',
  'CF': 'Central African Republic',
  'TD': 'Chad',
  'CL': 'Chile',
  'CN': 'China',
  'CX': 'Christmas Island',
  'CC': 'Cocos (Keeling) Islands',
  'CO': 'Colombia',
  'KM': 'Comoros',
  'CG': 'Congo Republic',
  'CK': 'Cook Islands',
  'CR': 'Costa Rica',
  'CI': "Cote d'Ivoire",
  'HR': 'Croatia',
  'CU': 'Cuba',
  'CW': 'Curacao',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'DK': 'Denmark',
  'DJ': 'Djibouti',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'CD': 'DR Congo',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'SV': 'El Salvador',
  'GQ': 'Equatorial Guinea',
  'ER': 'Eritrea',
  'EE': 'Estonia',
  'SZ': 'Eswatini',
  'ET': 'Ethiopia',
  'FO': 'Faroe Islands',
  'FK': 'Falkland Islands',
  'FJ': 'Fiji',
  'FI': 'Finland',
  'FR': 'France',
  'GF': 'French Guiana',
  'PF': 'French Polynesia',
  'TF': 'French Southern Territories',
  'GA': 'Gabon',
  'GM': 'Gambia',
  'GE': 'Georgia',
  'DE': 'Germany',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  '^GR$|^EL$': 'Greece',
  'GL': 'Greenland',
  'GD': 'Grenada',
  'GP': 'Guadeloupe',
  'GU': 'Guam',
  'GT': 'Guatemala',
  'GG': 'Guernsey',
  'GN': 'Guinea',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HT': 'Haiti',
  'HM': 'Heard and McDonald Islands',
  'HN': 'Honduras',
  'HK': 'Hong Kong',
  'HU': 'Hungary',
  'IS': 'Iceland',
  'IN': 'India',
  'ID': 'Indonesia',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'IE': 'Ireland',
  'IM': 'Isle of Man',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JP': 'Japan',
  'JE': 'Jersey',
  'JO': 'Jordan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KI': 'Kiribati',
  'XK': 'Kosovo',
  'KW': 'Kuwait',
  'KG': 'Kyrgyz Republic',
  'LA': 'Laos',
  'LV': 'Latvia',
  'LB': 'Lebanon',
  'LS': 'Lesotho',
  'LR': 'Liberia',
  'LY': 'Libya',
  'LI': 'Liechtenstein',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MO': 'Macau',
  'MK': 'North Macedonia',
  'MG': 'Madagascar',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'MV': 'Maldives',
  'ML': 'Mali',
  'MT': 'Malta',
  'MH': 'Marshall Islands',
  'MQ': 'Martinique',
  'MR': 'Mauritania',
  'MU': 'Mauritius',
  'YT': 'Mayotte',
  'MX': 'Mexico',
  'FM': 'Micronesia, Fed. Sts.',
  'MD': 'Moldova',
  'MC': 'Monaco',
  'MN': 'Mongolia',
  'ME': 'Montenegro',
  'MS': 'Montserrat',
  'MA': 'Morocco',
  'MZ': 'Mozambique',
  'MM': 'Myanmar',
  'NR': 'Nauru',
  'NP': 'Nepal',
  'NL': 'Netherlands',
  'AN': 'Netherlands Antilles',
  'NC': 'New Caledonia',
  'NZ': 'New Zealand',
  'NI': 'Nicaragua',
  'NE': 'Niger',
  'NG': 'Nigeria',
  'NU': 'Niue',
  'NF': 'Norfolk Island',
  'KP': 'North Korea',
  'MP': 'Northern Mariana Islands',
  'NO': 'Norway',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PW': 'Palau',
  'PS': 'Palestine',
  'PA': 'Panama',
  'PG': 'Papua New Guinea',
  'PY': 'Paraguay',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PN': 'Pitcairn',
  'PL': 'Poland',
  'PT': 'Portugal',
  'PR': 'Puerto Rico',
  'QA': 'Qatar',
  'RE': 'Reunion',
  'RO': 'Romania',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'MF': 'Saint-Martin',
  'WS': 'Samoa',
  'SM': 'San Marino',
  'ST': 'Sao Tome and Principe',
  'SA': 'Saudi Arabia',
  'SN': 'Senegal',
  'RS': 'Serbia',
  'SC': 'Seychelles',
  'SL': 'Sierra Leone',
  'SG': 'Singapore',
  'SX': 'Sint Maarten',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'SB': 'Solomon Islands',
  'SO': 'Somalia',
  'ZA': 'South Africa',
  'GS': 'South Georgia and South Sandwich Is.',
  'KR': 'South Korea',
  'SS': 'South Sudan',
  'SU': 'Soviet Union (former)',
  'ES': 'Spain',
  'LK': 'Sri Lanka',
  'BL': 'St. Barths',
  'SH': 'St. Helena',
  'KN': 'St. Kitts and Nevis',
  'LC': 'St. Lucia',
  'PM': 'St. Pierre and Miquelon',
  'VC': 'St. Vincent and the Grenadines',
  'SD': 'Sudan',
  'SR': 'Suriname',
  'SJ': 'Svalbard and Jan Mayen Islands',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'SY': 'Syria',
  'TW': 'Taiwan',
  'TJ': 'Tajikistan',
  'TZ': 'Tanzania',
  'TH': 'Thailand',
  'TL': 'Timor-Leste',
  'TG': 'Togo',
  'TK': 'Tokelau',
  'TO': 'Tonga',
  'TT': 'Trinidad and Tobago',
  'TN': 'Tunisia',
  'TR': 'Türkiye',
  'TM': 'Turkmenistan',
  'TC': 'Turks and Caicos Islands',
  'TV': 'Tuvalu',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'AE': 'United Arab Emirates',
  '^GB$|^UK$': 'United Kingdom',
  'US': 'United States',
  'UM': 'United States Minor Outlying Islands',
  'VI': 'United States Virgin Islands',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VU': 'Vanuatu',
  'VA': 'Vatican',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'WF': 'Wallis and Futuna Islands',
  'EH': 'Western Sahara',
  'YE': 'Yemen',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe'},
 'iso3_to_name_short': {'AFG': 'Afghanistan',
  'ALA': 'Aland Islands',
  'ALB': 'Albania',
  'DZA': 'Algeria',
  'ASM': 'American Samoa',
  'AND': 'Andorra',
  'AGO': 'Angola',
  'AIA': 'Anguilla',
  'ATA': 'Antarctica',
  'ATG': 'Antigua and Barbuda',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'ABW': 'Aruba',
  'AUS': 'Australia',
  'AUT': 'Austria',
  'AZE': 'Azerbaijan',
  'BHS': 'Bahamas',
  'BHR': 'Bahrain',
  'BGD': 'Bangladesh',
  'BRB': 'Barbados',
  'BLR': 'Belarus',
  'BEL': 'Belgium',
  'BLZ': 'Belize',
  'BEN': 'Benin',
  'BMU': 'Bermuda',
  'BTN': 'Bhutan',
  'BOL': 'Bolivia',
  'BES': 'Bonaire, Saint Eustatius and Saba',
  'BIH': 'Bosnia and Herzegovina',
  'BWA': 'Botswana',
  'BVT': 'Bouvet Island',
  'BRA': 'Brazil',
  'BA1': 'British Antarctic Territories',
  'IOT': 'British Indian Ocean Territory',
  'VGB': 'British Virgin Islands',
  'BRN': 'Brunei Darussalam',
  'BGR': 'Bulgaria',
  'BFA': 'Burkina Faso',
  'BDI': 'Burundi',
  'CPV': 'Cabo Verde',
  'KHM': 'Cambodia',
  'CMR': 'Cameroon',
  'CAN': 'Canada',
  'CYM': 'Cayman Islands',
  'CAF': 'Central African Republic',
  'TCD': 'Chad',
  'CHI': 'Channel Islands',
  'CHL': 'Chile',
  'CHN': 'China',
  'CXR': 'Christmas Island',
  'CCK': 'Cocos (Keeling) Islands',
  'COL': 'Colombia',
  'COM': 'Comoros',
  'COG': 'Congo Republic',
  'COK': 'Cook Islands',
  'CRI': 'Costa Rica',
  'CIV': "Cote d'Ivoire",
  'HRV': 'Croatia',
  'CUB': 'Cuba',
  'CUW': 'Curacao',
  'CYP': 'Cyprus',
  'CZE': 'Czechia',
  'DNK': 'Denmark',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'DOM': 'Dominican Republic',
  'COD': 'DR Congo',
  'ECU': 'Ecuador',
  'EGY': 'Egypt',
  'SLV': 'El Salvador',
  'GNQ': 'Equatorial Guinea',
  'ERI': 'Eritrea',
  'EST': 'Estonia',
  'SWZ': 'Eswatini',
  'ETH': 'Ethiopia',
  'FRO': 'Faroe Islands',
  'FLK': 'Falkland Islands',
  'FJI': 'Fiji',
  'FIN': 'Finland',
  'FRA': 'France',
  'GUF': 'French Guiana',
  'PYF': 'French Polynesia',
  'ATF': 'French Southern Territories',
  'GAB': 'Gabon',
  'GMB': 'Gambia',
  'GEO': 'Georgia',
  'DEU': 'Germany',
  'GHA': 'Ghana',
  'GIB': 'Gibraltar',
  'GRC': 'Greece',
  'GRL': 'Greenland',
  'GRD': 'Grenada',
  'GLP': 'Guadeloupe',
  'GUM': 'Guam',
  'GTM': 'Guatemala',
  'GGY': 'Guernsey',
  'GIN': 'Guinea',
  'GNB': 'Guinea-Bissau',
  'GUY': 'Guyana',
  'HTI': 'Haiti',
  'HMD': 'Heard and McDonald Islands',
  'HND': 'Honduras',
  'HKG': 'Hong Kong',
  'HUN': 'Hungary',
  'ISL': 'Iceland',
  'IND': 'India',
  'IDN': 'Indonesia',
  'IRN': 'Iran',
  'IRQ': 'Iraq',
  'IRL': 'Ireland',
  'IMN': 'Isle of Man',
  'ISR': 'Israel',
  'ITA': 'Italy',
  'JAM': 'Jamaica',
  'JPN': 'Japan',
  'JEY': 'Jersey',
  'JOR': 'Jordan',
  'KAZ': 'Kazakhstan',
  'KEN': 'Kenya',
  'KIR': 'Kiribati',
  'XKX': 'Kosovo',
  'KWT': 'Kuwait',
  'KGZ': 'Kyrgyz Republic',
  'LAO': 'Laos',
  'LVA': 'Latvia',
  'LBN': 'Lebanon',
  'LSO': 'Lesotho',
  'LBR': 'Liberia',
  'LBY': 'Libya',
  'LIE': 'Liechtenstein',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'MAC': 'Macau',
  'MKD': 'North Macedonia',
  'MDG': 'Madagascar',
  'MWI': 'Malawi',
  'MYS': 'Malaysia',
  'MDV': 'Maldives',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MHL': 'Marshall Islands',
  'MTQ': 'Martinique',
  'MRT': 'Mauritania',
  'MUS': 'Mauritius',
  'MYT': 'Mayotte',
  'MEX': 'Mexico',
  'FSM': 'Micronesia, Fed. Sts.',
  'MDA': 'Moldova',
  'MCO': 'Monaco',
  'MNG': 'Mongolia',
  'MNE': 'Montenegro',
  'MSR': 'Montserrat',
  'MAR': 'Morocco',
  'MOZ': 'Mozambique',
  'MMR': 'Myanmar',
  'NAM': 'Namibia',
  'NRU': 'Nauru',
  'NPL': 'Nepal',
  'NLD': 'Netherlands',
  'ANT': 'Netherlands Antilles',
  'NCL': 'New Caledonia',
  'NZL': 'New Zealand',
  'NIC': 'Nicaragua',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'NIU': 'Niue',
  'NFK': 'Norfolk Island',
  'PRK': 'North Korea',
  'MNP': 'Northern Mariana Islands',
  'NOR': 'Norway',
  'OMN': 'Oman',
  'PAK': 'Pakistan',
  'PLW': 'Palau',
  'PSE': 'Palestine',
  'PAN': 'Panama',
  'PNG': 'Papua New Guinea',
  'PRY': 'Paraguay',
  'PER': 'Peru',
  'PHL': 'Philippines',
  'PCN': 'Pitcairn',
  'POL': 'Poland',
  'PRT': 'Portugal',
  'PRI': 'Puerto Rico',
  'QAT': 'Qatar',
  'REU': 'Reunion',
  'ROU': 'Romania',
  'RUS': 'Russia',
  'RWA': 'Rwanda',
  'MAF': 'Saint-Martin',
  'WSM': 'Samoa',
  'SMR': 'San Marino',
  'STP': 'Sao Tome and Principe',
  'SAU': 'Saudi Arabia',
  'SEN': 'Senegal',
  'SRB': 'Serbia',
  'SYC': 'Seychelles',
  'SLE': 'Sierra Leone',
  'SGP': 'Singapore',
  'SXM': 'Sint Maarten',
  'SVK': 'Slovakia',
  'SVN': 'Slovenia',
  'SLB': 'Solomon Islands',
  'SOM': 'Somalia',
  'ZAF': 'South Africa',
  'SGS': 'South Georgia and South Sandwich Is.',
  'KOR': 'South Korea',
  'SSD': 'South Sudan',
  'SUN': 'Soviet Union (former)',
  'ESP': 'Spain',
  'LKA': 'Sri Lanka',
  'BLM': 'St. Barths',
  'SHN': 'St. Helena',
  'KNA': 'St. Kitts and Nevis',
  'LCA': 'St. Lucia',
  'SPM': 'St. Pierre and Miquelon',
  'VCT': 'St. Vincent and the Grenadines',
  'SDN': 'Sudan',
  'SUR': 'Suriname',
  'SJM': 'Svalbard and Jan Mayen Islands',
  'SWE': 'Sweden',
  'CHE': 'Switzerland',
  'SYR': 'Syria',
  'TWN': 'Taiwan',
  'TJK': 'Tajikistan',
  'EAT': 'Tanganjika',
  'TZA': 'Tanzania',
  'THA': 'Thailand',
  'TLS': 'Timor-Leste',
  'TGO': 'Togo',
  'TKL': 'Tokelau',
  'TON': 'Tonga',
  'TTO': 'Trinidad and Tobago',
  'TUN': 'Tunisia',
  'TUR': 'Türkiye',
  'TKM': 'Turkmenistan',
  'TCA': 'Turks and Caicos Islands',
  'TUV': 'Tuvalu',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'ARE': 'United Arab Emirates',
  'GBR': 'United Kingdom',
  'USA': 'United States',
  'UMI': 'United States Minor Outlying Islands',
  'VIR': 'United States Virgin Islands',
  'URY': 'Uruguay',
  'UZB': 'Uzbekistan',
  'VUT': 'Vanuatu',
  'VAT': 'Vatican',
  'VEN': 'Venezuela',
  'VNM': 'Vietnam',
  'WLF': 'Wallis and Futuna Islands',
  'ESH': 'Western Sahara',
  'YEM': 'Yemen',
  'ZMB': 'Zambia',
  'EAZ': 'Zanzibar',
  'ZWE': 'Zimbabwe'},
 'name_short_to_iso2': {'Afghanistan': 'AF',
  'Euro area (20 countries)' : 'ECB',
  'Aland Islands': 'AX',
  'Albania': 'AL',
  'Algeria': 'DZ',
  'American Samoa': 'AS',
  'Andorra': 'AD',
  'Angola': 'AO',
  'Anguilla': 'AI',
  'Antarctica': 'AQ',
  'Antigua and Barbuda': 'AG',
  'Argentina': 'AR',
  'Armenia': 'AM',
  'Aruba': 'AW',
  'Australia': 'AU',
  'Austria': 'AT',
  'Azerbaijan': 'AZ',
  'Bahamas': 'BS',
  'Bahrain': 'BH',
  'Bangladesh': 'BD',
  'Barbados': 'BB',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'Belize': 'BZ',
  'Benin': 'BJ',
  'Bermuda': 'BM',
  'Bhutan': 'BT',
  'Bolivia': 'BO',
  'Bonaire, Saint Eustatius and Saba': 'BQ',
  'Bosnia and Herzegovina': 'BA',
  'Botswana': 'BW',
  'Bouvet Island': 'BV',
  'Brazil': 'BR',
  'British Antarctic Territories': 'B1',
  'British Indian Ocean Territory': 'IO',
  'British Virgin Islands': 'VG',
  'Brunei Darussalam': 'BN',
  'Bulgaria': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cabo Verde': 'CV',
  'Cambodia': 'KH',
  'Cameroon': 'CM',
  'Canada': 'CA',
  'Cape Verde': 'CV',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  'Chad': 'TD',
  'Chile': 'CL',
  r'China( mainland)?': 'CN',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  'Colombia': 'CO',
  'Comoros': 'KM',
  'Congo Democratic Republic': 'CD',
  '^Congo Republic|^Congo, Republic of the$': 'CG',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  "Cote d'Ivoire": 'CI',
  'Croatia': 'HR',
  'Cuba': 'CU',
  'Curacao': 'CW',
  'Cyprus': 'CY',
  #'Czechia': 'CZ',
  '^Czechia$|^Czech Republic$': 'CZ',
  'Denmark': 'DK',
  'Djibouti': 'DJ',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'DR Congo': 'CD',
  'Ecuador': 'EC',
  #'Egypt': 'EG',
  r'^Egypt$|^Egypt, Arab Rep\.$': 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Estonia': 'EE',
  'Eswatini': 'SZ',
  'Ethiopia': 'ET',
  'Eurozone': 'EU',
  'Faroe Islands': 'FO',
  'Falkland Islands': 'FK',
  'Fiji': 'FJ',
  'Finland': 'FI',
  'France': 'FR',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  'Gabon': 'GA',
  #'Gambia': 'GM',
  '^Gambia$|^Gambia, The$': 'GM',
  'Georgia': 'GE',
  'Germany': 'DE',
  'Ghana': 'GH',
  'Gibraltar': 'GI',
  'Greece': 'GR',
  'Greenland': 'GL',
  'Grenada': 'GD',
  'Guadeloupe': 'GP',
  'Guam': 'GU',
  'Guatemala': 'GT',
  'Guernsey': 'GG',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Haiti': 'HT',
  'Heard and McDonald Islands': 'HM',
  'Honduras': 'HN',
  '^Hong Kong|Hong Kong SAR$': 'HK',
  'Hungary': 'HU',
  'Iceland': 'IS',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran': 'IR',
  'Iraq': 'IQ',
  'Ireland': 'IE',
  'Isle of Man': 'IM',
  'Israel': 'IL',
  'Italy': 'IT',
  'Jamaica': 'JM',
  'Japan': 'JP',
  'Jersey': 'JE',
  'Jordan': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kiribati': 'KI',
  'Kosovo': 'XK',
  'Kuwait': 'KW',
  'Kyrgyz Republic': 'KG',
  'Laos': 'LA',
  'Latvia': 'LV',
  'Lebanon': 'LB',
  'Lesotho': 'LS',
  'Liberia': 'LR',
  'Libya': 'LY',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Macau': 'MO',
  '^North Macedonia|^Macedonia, North$': 'MK',
  'Madagascar': 'MG',
  'Malawi': 'MW',
  'Malaysia': 'MY',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malta': 'MT',
  'Marshall Islands': 'MH',
  'Martinique': 'MQ',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Mayotte': 'YT',
  'Mexico': 'MX',
  'Micronesia, Fed. Sts.': 'FM',
  'Moldova': 'MD',
  'Monaco': 'MC',
  'Mongolia': 'MN',
  'Montenegro': 'ME',
  'Montserrat': 'MS',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  r'Myanmar( Burma)?': 'MM',
  'Namibia': 'NA',
  'Nauru': 'NR',
  'Nepal': 'NP',
  'Netherlands': 'NL',
  'Netherlands Antilles': 'AN',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  'Nicaragua': 'NI',
  'Nigeria': 'NG',
  'Niger': 'NE',
  'Niue': 'NU',
  'Norfolk Island': 'NF',
  'North Korea': 'KP',
  'Northern Mariana Islands': 'MP',
  'Norway': 'NO',
  'Oman': 'OM',
  'Pakistan': 'PK',
  'Palau': 'PW',
  'Palestine': 'PS',
  'Panama': 'PA',
  'Papua New Guinea': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Philippines': 'PH',
  'Pitcairn': 'PN',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Puerto Rico': 'PR',
  'Qatar': 'QA',
  'Reunion': 'RE',
  'Romania': 'RO',
  'Russia': 'RU',
  'Rwanda': 'RW',
  'Saint-Martin': 'MF',
  'Samoa': 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  'Senegal': 'SN',
  'St Kitts and Nevis': 'KN',
  'Serbia': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapore': 'SG',
  'Sint Maarten': 'SX',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Solomon Islands': 'SB',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'South Georgia and South Sandwich Is.': 'GS',
  #'South Korea': 'KR',
  #'^South Korea$|^Korea, Rep\\.$': 'KR',  
  '^South Korea$|^Korea, Rep\\.$|^Korea$': 'KR',
  'South Sudan': 'SS',
  'Soviet Union (former)': 'SU',
  'Spain': 'ES',
  'Sri Lanka': 'LK',
  'St. Barths': 'BL',
  'St. Helena': 'SH',
  'St. Kitts and Nevis': 'KN',
  '^St. Lucia|^St Lucia$': 'LC',
  'St. Pierre and Miquelon': 'PM',
  '^St. Vincent and the Grenadines|^St Vincent and the Grenadines$': 'VC',
  'Sudan': 'SD',
  'Suriname': 'SR',
  'Svalbard and Jan Mayen Islands': 'SJ',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Syria': 'SY',
  'Taiwan': 'TW',
  'Tajikistan': 'TJ',
  'Tanzania': 'TZ',
  'Thailand': 'TH',
  'Timor-Leste': 'TL',
  'Togo': 'TG',
  'Tokelau': 'TK',
  'Tonga': 'TO',
  'Trinidad and Tobago': 'TT',
  'Tunisia': 'TN',
  #'Türkiye': 'TR',
  '^Türkiye$|^Turkey$': 'TR',
  'Turkmenistan': 'TM',
  'Turks and Caicos Islands': 'TC',
  'Tuvalu': 'TV',
  'Uganda': 'UG',
  'Ukraine': 'UA',
  'United Arab Emirates': 'AE',
  #'United Kingdom': '^GB$|^UK$',
  '^United Kingdom$|^UK$|^GB$': 'GB',
  'United States': 'US',
  'United States Minor Outlying Islands': 'UM',
  'United States Virgin Islands': 'VI',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vanuatu': 'VU',
  'Vatican': 'VA',
  'Venezuela': 'VE',
  'Vietnam': 'VN',
  'Wallis and Futuna Islands': 'WF',
  'Western Sahara': 'EH',
  'Yemen': 'YE',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW'},
 'name_short_to_iso3': {'Afghanistan': 'AFG',
  'Aland Islands': 'ALA',
  'Albania': 'ALB',
  'Algeria': 'DZA',
  'American Samoa': 'ASM',
  'Andorra': 'AND',
  'Angola': 'AGO',
  'Anguilla': 'AIA',
  'Antarctica': 'ATA',
  'Antigua and Barbuda': 'ATG',
  'Argentina': 'ARG',
  'Armenia': 'ARM',
  'Aruba': 'ABW',
  'Australia': 'AUS',
  'Austria': 'AUT',
  'Azerbaijan': 'AZE',
  'Bahamas': 'BHS',
  'Bahrain': 'BHR',
  'Bangladesh': 'BGD',
  'Barbados': 'BRB',
  'Belarus': 'BLR',
  'Belgium': 'BEL',
  'Belize': 'BLZ',
  'Benin': 'BEN',
  'Bermuda': 'BMU',
  'Bhutan': 'BTN',
  'Bolivia': 'BOL',
  'Bonaire, Saint Eustatius and Saba': 'BES',
  'Bosnia and Herzegovina': 'BIH',
  'Botswana': 'BWA',
  'Bouvet Island': 'BVT',
  'Brazil': 'BRA',
  'British Antarctic Territories': 'BA1',
  'British Indian Ocean Territory': 'IOT',
  'British Virgin Islands': 'VGB',
  'Brunei Darussalam': 'BRN',
  'Bulgaria': 'BGR',
  'Burkina Faso': 'BFA',
  'Burundi': 'BDI',
  'Cabo Verde': 'CPV',
  'Cambodia': 'KHM',
  'Cameroon': 'CMR',
  'Canada': 'CAN',
  'Cayman Islands': 'CYM',
  'Central African Republic': 'CAF',
  'Chad': 'TCD',
  'Channel Islands': 'CHI',
  'Chile': 'CHL',
  'China': 'CHN',
  'Christmas Island': 'CXR',
  'Cocos (Keeling) Islands': 'CCK',
  'Colombia': 'COL',
  'Comoros': 'COM',
  'Congo Republic': 'COG',
  'Cook Islands': 'COK',
  'Costa Rica': 'CRI',
  "Cote d'Ivoire": 'CIV',
  'Croatia': 'HRV',
  'Cuba': 'CUB',
  'Curacao': 'CUW',
  'Cyprus': 'CYP',
  'Czechia': 'CZE',
  'Denmark': 'DNK',
  'Djibouti': 'DJI',
  'Dominica': 'DMA',
  'Dominican Republic': 'DOM',
  'DR Congo': 'COD',
  'Ecuador': 'ECU',
  'Egypt': 'EGY',
  'El Salvador': 'SLV',
  'Equatorial Guinea': 'GNQ',
  'Eritrea': 'ERI',
  'Estonia': 'EST',
  'Eswatini': 'SWZ',
  'Ethiopia': 'ETH',
  'Faroe Islands': 'FRO',
  'Falkland Islands': 'FLK',
  'Fiji': 'FJI',
  'Finland': 'FIN',
  'France': 'FRA',
  'French Guiana': 'GUF',
  'French Polynesia': 'PYF',
  'French Southern Territories': 'ATF',
  'Gabon': 'GAB',
  'Gambia': 'GMB',
  'Georgia': 'GEO',
  'Germany': 'DEU',
  'Ghana': 'GHA',
  'Gibraltar': 'GIB',
  'Greece': 'GRC',
  'Greenland': 'GRL',
  'Grenada': 'GRD',
  'Guadeloupe': 'GLP',
  'Guam': 'GUM',
  'Guatemala': 'GTM',
  'Guernsey': 'GGY',
  'Guinea': 'GIN',
  'Guinea-Bissau': 'GNB',
  'Guyana': 'GUY',
  'Haiti': 'HTI',
  'Heard and McDonald Islands': 'HMD',
  'Honduras': 'HND',
  'Hong Kong': 'HKG',
  'Hungary': 'HUN',
  'Iceland': 'ISL',
  'India': 'IND',
  'Indonesia': 'IDN',
  'Iran': 'IRN',
  'Iraq': 'IRQ',
  'Ireland': 'IRL',
  'Isle of Man': 'IMN',
  'Israel': 'ISR',
  'Italy': 'ITA',
  'Jamaica': 'JAM',
  'Japan': 'JPN',
  'Jersey': 'JEY',
  'Jordan': 'JOR',
  'Kazakhstan': 'KAZ',
  'Kenya': 'KEN',
  'Kiribati': 'KIR',
  'Kosovo': 'XKX',
  'Kuwait': 'KWT',
  'Kyrgyz Republic': 'KGZ',
  'Laos': 'LAO',
  'Latvia': 'LVA',
  'Lebanon': 'LBN',
  'Lesotho': 'LSO',
  'Liberia': 'LBR',
  'Libya': 'LBY',
  'Liechtenstein': 'LIE',
  'Lithuania': 'LTU',
  'Luxembourg': 'LUX',
  'Macau': 'MAC',
  'North Macedonia': 'MKD',
  'Madagascar': 'MDG',
  'Malawi': 'MWI',
  'Malaysia': 'MYS',
  'Maldives': 'MDV',
  'Mali': 'MLI',
  'Malta': 'MLT',
  'Marshall Islands': 'MHL',
  'Martinique': 'MTQ',
  'Mauritania': 'MRT',
  'Mauritius': 'MUS',
  'Mayotte': 'MYT',
  'Mexico': 'MEX',
  'Micronesia, Fed. Sts.': 'FSM',
  'Moldova': 'MDA',
  'Monaco': 'MCO',
  'Mongolia': 'MNG',
  'Montenegro': 'MNE',
  'Montserrat': 'MSR',
  'Morocco': 'MAR',
  'Mozambique': 'MOZ',
  'Myanmar': 'MMR',
  'Namibia': 'NAM',
  'Nauru': 'NRU',
  'Nepal': 'NPL',
  'Netherlands': 'NLD',
  'Netherlands Antilles': 'ANT',
  'New Caledonia': 'NCL',
  'New Zealand': 'NZL',
  'Nicaragua': 'NIC',
  'Niger': 'NER',
  'Nigeria': 'NGA',
  'Niue': 'NIU',
  'Norfolk Island': 'NFK',
  'North Korea': 'PRK',
  'Northern Mariana Islands': 'MNP',
  'Norway': 'NOR',
  'Oman': 'OMN',
  'Pakistan': 'PAK',
  'Palau': 'PLW',
  'Palestine': 'PSE',
  'Panama': 'PAN',
  'Papua New Guinea': 'PNG',
  'Paraguay': 'PRY',
  'Peru': 'PER',
  'Philippines': 'PHL',
  'Pitcairn': 'PCN',
  'Poland': 'POL',
  'Portugal': 'PRT',
  'Puerto Rico': 'PRI',
  'Qatar': 'QAT',
  'Reunion': 'REU',
  'Romania': 'ROU',
  'Russia': 'RUS',
  'Rwanda': 'RWA',
  'Saint-Martin': 'MAF',
  'Samoa': 'WSM',
  'San Marino': 'SMR',
  'Sao Tome and Principe': 'STP',
  'Saudi Arabia': 'SAU',
  'Senegal': 'SEN',
  'Serbia': 'SRB',
  'Seychelles': 'SYC',
  'Sierra Leone': 'SLE',
  'Singapore': 'SGP',
  'Sint Maarten': 'SXM',
  'Slovakia': 'SVK',
  'Slovenia': 'SVN',
  'Solomon Islands': 'SLB',
  'Somalia': 'SOM',
  'South Africa': 'ZAF',
  'South Georgia and South Sandwich Is.': 'SGS',
  'South Korea': 'KOR',
  'South Sudan': 'SSD',
  'Soviet Union (former)': 'SUN',
  'Spain': 'ESP',
  'Sri Lanka': 'LKA',
  'St. Barths': 'BLM',
  'St. Helena': 'SHN',
  'St. Kitts and Nevis': 'KNA',
  'St. Lucia': 'LCA',
  'St. Pierre and Miquelon': 'SPM',
  'St. Vincent and the Grenadines': 'VCT',
  'Sudan': 'SDN',
  'Suriname': 'SUR',
  'Svalbard and Jan Mayen Islands': 'SJM',
  'Sweden': 'SWE',
  'Switzerland': 'CHE',
  'Syria': 'SYR',
  'Taiwan': 'TWN',
  'Tajikistan': 'TJK',
  'Tanganjika': 'EAT',
  'Tanzania': 'TZA',
  'Thailand': 'THA',
  'Timor-Leste': 'TLS',
  'Togo': 'TGO',
  'Tokelau': 'TKL',
  'Tonga': 'TON',
  'Trinidad and Tobago': 'TTO',
  'Tunisia': 'TUN',
  'Türkiye': 'TUR',
  'Turkmenistan': 'TKM',
  'Turks and Caicos Islands': 'TCA',
  'Tuvalu': 'TUV',
  'Uganda': 'UGA',
  'Ukraine': 'UKR',
  'United Arab Emirates': 'ARE',
  'United Kingdom': 'GBR',
  'United States': 'USA',
  'United States Minor Outlying Islands': 'UMI',
  'United States Virgin Islands': 'VIR',
  'Uruguay': 'URY',
  'Uzbekistan': 'UZB',
  'Vanuatu': 'VUT',
  'Vatican': 'VAT',
  'Venezuela': 'VEN',
  'Vietnam': 'VNM',
  'Wallis and Futuna Islands': 'WLF',
  'Western Sahara': 'ESH',
  'Yemen': 'YEM',
  'Zambia': 'ZMB',
  'Zanzibar': 'EAZ',
  'Zimbabwe': 'ZWE'}}

# Manual fixes for typical merge issues
dict_country["iso2_to_iso3"].update({
    "GB": "GBR",
    "UK": "GBR",
    "GR": "GRC",
    "EL": "GRC",
})

dict_country["name_short_to_iso3"].update({
    "Korea": "KOR",
    "UK": "GBR",
    "US": "USA",
    "Mainland China": "CHN",
    "SCMP China": "CHN",
})

