data:
  raw_data_file: data/examples/academic/ghysels_2018/Ch_8/bvar_simulated_ch8_sec4.csv

model:
  model_type: bvar
  target_variables:
    - x
    - y
  lags: 4
  lambda1: 0.2
  lambda2: 0.99
  lambda3: 1.0
  n_draws: 500
